# -*- coding: utf-8 -*-
"""dash_moneter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktPfWaQomo0VXt4lSkVSqXAI-xboKALQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# import plotly.graph_objects as go
# 
# st.set_page_config(page_title="Market Dashboard", layout="wide")
# st.title("📈 Financial Market Dashboard")
# 
# @st.cache_data
# def load_data():
#     # Pastikan file db_dashboard.xlsx sudah Anda upload ke Google Colab!
#     df = pd.read_excel('db_dashboard.xlsx')
#     df.rename(columns={df.columns[0]: 'Date'}, inplace=True)
#     df['Date'] = pd.to_datetime(df['Date'])
#     df = df.sort_values('Date').reset_index(drop=True)
#     return df
# 
# df = load_data()
# 
# def calculate_metrics(df):
#     df_desc = df.sort_values('Date', ascending=False).reset_index(drop=True)
#     latest_date = df_desc['Date'].iloc[0]
#     latest_year = latest_date.year
# 
#     def get_past_value(target_date, col):
#         past_data = df_desc[df_desc['Date'] <= target_date]
#         if not past_data.empty:
#             return past_data.iloc[0][col]
#         return None
# 
#     dod_date = df_desc['Date'].iloc[1] if len(df_desc) > 1 else latest_date
#     wow_date = latest_date - pd.Timedelta(days=7)
#     mom_date = latest_date - pd.Timedelta(days=30)
#     ytd_date = pd.to_datetime(f"{latest_year - 1}-12-31")
#     yoy_date = latest_date - pd.Timedelta(days=365)
# 
#     metrics = []
#     columns_to_check = ['Rupiah', 'IHSG', 'UST10Y', 'SBN10Y']
# 
#     for col in columns_to_check:
#         latest_val = df_desc.iloc[0][col]
#         val_dod = get_past_value(dod_date, col)
#         val_wow = get_past_value(wow_date, col)
#         val_mom = get_past_value(mom_date, col)
#         val_ytd = get_past_value(ytd_date, col)
#         val_yoy = get_past_value(yoy_date, col)
# 
#         def calc_pct(current, past):
#             if past is None or past == 0: return "N/A"
#             pct = ((current - past) / past) * 100
#             return f"{pct:+.2f}%"
# 
#         metrics.append({
#             'Indicator': col,
#             'Latest Value': f"{latest_val:,.2f}" if col in ['IHSG', 'Rupiah'] else f"{latest_val:.4f}",
#             'Day to Day (DoD)': calc_pct(latest_val, val_dod),
#             'Week to Date (WtD)': calc_pct(latest_val, val_wow),
#             'Month to Date (MtD)': calc_pct(latest_val, val_mom),
#             'Year to Date (YTD)': calc_pct(latest_val, val_ytd),
#             'Year on Year (YoY)': calc_pct(latest_val, val_yoy)
#         })
# 
#     return pd.DataFrame(metrics).set_index('Indicator')
# 
# st.subheader("📊 Market Performance Overview")
# metrics_df = calculate_metrics(df)
# st.dataframe(metrics_df, use_container_width=True)
# st.markdown("---")
# st.subheader("📈 Market Trends")
# 
# col1, col2 = st.columns(2)
# with col1:
#     fig_rupiah = px.line(df, x='Date', y='Rupiah', title='Rupiah (USD/IDR) Trend')
#     fig_rupiah.update_layout(xaxis_title="", yaxis_title="Rupiah", hovermode="x unified")
#     st.plotly_chart(fig_rupiah, use_container_width=True)
# 
# with col2:
#     fig_ihsg = px.line(df, x='Date', y='IHSG', title='IHSG Trend')
#     fig_ihsg.update_layout(xaxis_title="", yaxis_title="Index Level", hovermode="x unified")
#     fig_ihsg.update_traces(line_color='green')
#     st.plotly_chart(fig_ihsg, use_container_width=True)
# 
# st.markdown("### Bond Yields (10-Year)")
# fig_bonds = go.Figure()
# fig_bonds.add_trace(go.Scatter(x=df['Date'], y=df['UST10Y'], mode='lines', name='US Treasury 10Y', line=dict(color='blue')))
# fig_bonds.add_trace(go.Scatter(x=df['Date'], y=df['SBN10Y'], mode='lines', name='Indonesian Govt Bond 10Y', line=dict(color='orange')))
# fig_bonds.update_layout(title='Comparison of SBN10Y and UST10Y', xaxis_title="Date", yaxis_title="Yield (%)", hovermode="x unified", legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
# st.plotly_chart(fig_bonds, use_container_width=True)