# -*- coding: utf-8 -*-
"""dash_moneter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktPfWaQomo0VXt4lSkVSqXAI-xboKALQ
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from datetime import timedelta
import os

# Set Page Config
st.set_page_config(page_title="Market Dashboard", layout="wide")

# Nama file
FILE_NAME = 'db_dashboard.xlsx - Sheet1.csv'

# Check if file exists
if not os.path.exists(FILE_NAME):
    st.error(f"File '{FILE_NAME}' tidak ditemukan! Pastikan file berada di folder yang sama dengan script ini.")
    st.stop()

@st.cache_data
def load_data():
    df = pd.read_csv(FILE_NAME)
    df.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date')
    return df

try:
    df = load_data()
    latest_date = df['Date'].max()

    # --- HEADER ---
    st.title("📈 Market Analysis Dashboard")
    st.markdown(f"**Data Terakhir: {latest_date.strftime('%d %B %Y')}**")

    # Fungsi Kalkulasi Metrik
    def get_metrics(df, asset_col):
        latest_val = df[asset_col].iloc[-1]

        # DTD
        prev_day = df[asset_col].iloc[-2]
        dtd = ((latest_val / prev_day) - 1) * 100

        # WTW
        prev_week_date = latest_date - timedelta(days=7)
        prev_week_val = df[df['Date'] <= prev_week_date][asset_col].iloc[-1]
        wtw = ((latest_val / prev_week_val) - 1) * 100

        # MTM
        prev_month_end = latest_date.replace(day=1) - timedelta(days=1)
        prev_month_val = df[df['Date'] <= prev_month_end][asset_col].iloc[-1]
        mtm = ((latest_val / prev_month_val) - 1) * 100

        # YTD
        prev_year_end = latest_date.replace(month=1, day=1) - timedelta(days=1)
        prev_year_val = df[df['Date'] <= prev_year_end][asset_col].iloc[-1]
        ytd = ((latest_val / prev_year_val) - 1) * 100

        # YoY
        yoy_date = latest_date - pd.DateOffset(years=1)
        prev_yoy_val = df[df['Date'] <= yoy_date][asset_col].iloc[-1]
        yoy = ((latest_val / prev_yoy_val) - 1) * 100

        return [latest_val, dtd, wtw, mtm, ytd, yoy]

    # Tabel Summary
    assets = ['Rupiah', 'IHSG', 'UST10Y', 'SBN10Y']
    summary_list = []
    for asset in assets:
        summary_list.append([asset] + get_metrics(df, asset))

    summary_df = pd.DataFrame(summary_list, columns=['Asset', 'Latest', 'DTD (%)', 'WTW (%)', 'MTM (%)', 'YTD (%)', 'YoY (%)'])

    st.subheader("Market Performance Summary")
    st.dataframe(summary_df.style.format({
        'Latest': '{:,.2f}', 'DTD (%)': '{:+.2f}%', 'WTW (%)': '{:+.2f}%',
        'MTM (%)': '{:+.2f}%', 'YTD (%)': '{:+.2f}%', 'YoY (%)': '{:+.2f}%'
    }), use_container_width=True)

    # --- GRAFIK ---
    col1, col2 = st.columns(2)
    with col1:
        fig_ihsg = go.Figure(go.Scatter(x=df['Date'], y=df['IHSG'], name='IHSG', line=dict(color='orange')))
        fig_ihsg.update_layout(title="IHSG Trend", template="plotly_dark")
        st.plotly_chart(fig_ihsg, use_container_width=True)

    with col2:
        fig_idr = go.Figure(go.Scatter(x=df['Date'], y=df['Rupiah'], name='USD/IDR', line=dict(color='green')))
        fig_idr.update_layout(title="Rupiah Trend", template="plotly_dark")
        st.plotly_chart(fig_idr, use_container_width=True)

    st.subheader("Yield Comparison: SBN 10Y vs UST 10Y")
    fig_yield = go.Figure()
    fig_yield.add_trace(go.Scatter(x=df['Date'], y=df['SBN10Y'], name='SBN 10Y'))
    fig_yield.add_trace(go.Scatter(x=df['Date'], y=df['UST10Y'], name='UST 10Y'))
    fig_yield.update_layout(template="plotly_dark", hovermode="x unified")
    st.plotly_chart(fig_yield, use_container_width=True)

except Exception as e:
    st.error(f"Terjadi kesalahan saat memproses data: {e}")